### ISSUE TITLE
composer.json and modman file

### ISSUE THREAD

**Issue by SchumacherFM** [tobias-forkel/Forkel_Counter#1]
Hey Tobi,

despite this project is pretty awesome not all of use will use it because the composer.json and modman files are missing. Please add those two files :-)

Cheers

**Comment by tobias-forkel** [comment]
Hi Schumacher

I'll commit the files for composer and modman asap and let you know.

Tobi

**Comment by tobias-forkel** [comment]
Done. Gruss

**Comment by SchumacherFM** [comment]
Muchias Gracias!
